apiVersion: v1
kind: ServiceAccount
metadata:
  name: middle
---
apiVersion: v1
kind: Service
metadata:
  name: middle
  labels:
    app: middle
    service: middle
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: middle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      serviceAccountName: middle
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: cybwan/mtls-egress-demo-middle
        imagePullPolicy: Always
        name: middle
        command: ["/middle"]
        ports:
        - containerPort: 8080
